### ISSUE TITLE
Разместить форму инфы о пользователе в одну колонку и убрать лишние стили, если они есть

### ISSUE THREAD

**Issue by VeselAbaya** [VeselAbaya/diplom-recruting#34]
![Screenshot from 2021-11-12 11-15-49](https://user-images.githubusercontent.com/31548180/141433769-786e989b-4bf0-4e45-8713-5193f2df9806.png)

Сейчас форма разбивается на две колонки и выглядит это не очень

**Comment by mundisyum** [comment]
Баг не воспроизвёлся. Тестил в хроме и в фаерфоксе
![localhost_4200_search_e10fa77e-7f7d-4cfa-9c0c-9ceef614831c (2)](https://user-images.githubusercontent.com/6430448/141518877-4f94041d-7c88-42a8-96c1-c34d9c90cbcb.png)

**Comment by VeselAbaya** [comment]
Попробуй поувеличивать масштаб или вертикальный размер вьбпорта

**Comment by VeselAbaya** [comment]
> Баг не воспроизвёлся. Тестил в хроме и в фаерфоксе ![localhost_4200_search_e10fa77e-7f7d-4cfa-9c0c-9ceef614831c (2)](https://user-images.githubusercontent.com/6430448/141518877-4f94041d-7c88-42a8-96c1-c34d9c90cbcb.png)

Попробуй поувеличивать масштаб или вертикальный размер вьбпорта

**Comment by VeselAbaya** [comment]
Попробуй поувеличивать масштаб или вертикальный размер вьбпорта
